### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by xylo11** [xylo11/protospace-39340#1]
#URL
https://protospace-39340.onrender.com

**Comment by mo1015** [comment]
@xylo11 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [ ] **ログイン状態では、トップページに「こんにちは、〇〇さん」とユーザー名が表示されていること**
2箇所表示されているので修正しましょう。

- [ ] **正しくフォームを入力すると、コメントが投稿できること**
エラーページに遷移してしまい投稿できません。

- [ ] **フォームを空のまま投稿しようとすると、投稿できずにそのページに留まること**
エラーページに遷移してしまいます。

- [ ] **ログイン・ログアウトの状態に関わらず、ユーザーの詳細ページには、そのユーザーの詳細情報（名前・プロフィール・所属・役職）と、そのユーザーが投稿したプロトタイプが表示されていること**
ユーザーの詳細情報が表示されていません。
<img width="509" alt="スクリーンショット 2023-05-18 16 07 59" src="https://github.com/xylo11/protospace-39340/assets/62644781/e7bfdb0b-ad1c-4d44-9fcb-98729a4c3efd">


修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下のProtoSpace完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by xylo11** [comment]
ご指摘の修正箇所について修正及び確認が完了しました。
ご確認お願いします。

**Comment by xylo11** [comment]
〇〇さんのプロトタイプに修正しました。

**Comment by motomuun** [comment]
@xylo11 さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
